#cloud-config

write_files:
  - path: /etc/systemd/system/kingmaker-discord-bot.service
    content: |
      [Unit]
      Description=Kingmaker Discord Bot
      After=network.target
      
      [Service]
      ExecStart=/opt/kingmaker-discord-bot/Application
      Restart=always
      EnvironmentFile=/etc/profile.d/envvars.sh
      
      [Install]
      WantedBy=multi-user.target
  
  - path: /etc/profile.d/envvars.sh
    content: |
      AWS__LOGGROUP={{ LOG_GROUP }};
      AWS__REGION={{ REGION }};
      HEARTBEAT__INSTANCEDIMENSIONNAME={{ HEARTBEAT_INSTANCE_DIMENSION_NAME }}
      HEARTBEAT__INTERVALINSECONDS={{ HEARTBEAT_INTERVAL_IN_SECONDS }};
      HEARTBEAT__METRICNAME={{ HEARTBEAT_METRIC_NAME }};
      HEARTBEAT__NAMESPACE={{ HEARTBEAT_NAMESPACE }};

runcmd:
  - curl https://s3.us-east-2.amazonaws.com/aws-xray-assets.us-east-2/xray-daemon/aws-xray-daemon-3.x.rpm -o /home/ec2-user/xray.rpm
  - yum install -y /home/ec2-user/xray.rpm
  - mkdir -p /opt/kingmaker-discord-bot
  - aws s3 sync s3://{{ BUCKET }}/ /opt/kingmaker-discord-bot
  - chmod +x /opt/kingmaker-discord-bot/Application
  - systemctl daemon-reload
  - systemctl enable kingmaker-discord-bot
  - systemctl start kingmaker-discord-bot
