#cloud-config

write_files:
  - path: /etc/systemd/system/kingmaker-discord-bot.service
    content: |
      [Unit]
      Description=Kingmaker Discord Bot
      After=network.target
      
      [Service]
      ExecStart=/opt/kingmaker-discord-bot/Application
      Restart=always
      EnvironmentFile=/etc/profile.d/envvars.sh
      
      [Install]
      WantedBy=multi-user.target
  
  - path: /etc/profile.d/envvars.sh
    content: |
      AWS__LOGGROUP={{ LOG_GROUP }};
      AWS__REGION={{ REGION }};
      CLOUDWATCH__HEARTBEATINTERVALINSECONDS={{ HEARTBEAT_INTERVAL_IN_SECONDS }};
      CLOUDWATCH__METRICNAME={{ HEARTBEAT_METRIC_NAME }};
      CLOUDWATCH__NAMESPACE={{ HEARTBEAT_NAMESPACE }};

runcmd:
  - mkdir -p /opt/kingmaker-discord-bot
  - aws s3 sync s3://{{ BUCKET }}/ /opt/kingmaker-discord-bot
  - chmod +x /opt/kingmaker-discord-bot/Application
  - systemctl daemon-reload
  - systemctl enable kingmaker-discord-bot
  - systemctl start kingmaker-discord-bot
