#cloud-config

write_files:
  - path: /etc/systemd/system/kingmaker-discord-bot.service
    content: |
      [Unit]
      Description=Kingmaker Discord Bot
      After=network.target
      
      [Service]
      ExecStart=/opt/kingmaker-discord-bot/Application
      Restart=always
      EnvironmentFile=/etc/profile.d/envvars.sh
      
      [Install]
      WantedBy=multi-user.target
  
  - path: /etc/profile.d/envvars.sh
    content: |
      AWS_REGION={{ REGION }}
      AWS__LOGGROUP={{ LOG_GROUP }}
      AWS__REGION={{ REGION }}
      DISCORD__TOKENARN={{ DISCORD_TOKEN_ARN }}
      HEARTBEAT__INSTANCEDIMENSIONNAME={{ HEARTBEAT_INSTANCE_DIMENSION_NAME }}
      HEARTBEAT__INTERVALINSECONDS={{ HEARTBEAT_INTERVAL_IN_SECONDS }}
      HEARTBEAT__METRICNAME={{ HEARTBEAT_METRIC_NAME }}
      HEARTBEAT__NAMESPACE={{ HEARTBEAT_NAMESPACE }}

  - path: /etc/amazon/amazon-cloudwatch-agent.json
    content: |
      {
        "agent": {
          "metrics_collection_interval": 60,
          "run_as_user": "root"
        },
        "metrics": {
          "append_dimensions": {
            "InstanceId": "${aws:InstanceId}"
          },
          "metrics_collected": {
            "cpu": {
              "measurement": [
                "cpu_usage_idle",
                "cpu_usage_user",
                "cpu_usage_system"
              ],
              "totalcpu": true
            },
            "mem": {
              "measurement": [
                "mem_used_percent"
              ]
            },
            "disk": {
              "measurement": [
                "used_percent"
              ],
              "resources": [
                "/"
              ]
            },
            "swap": {
              "measurement": [
                "swap_used_percent"
              ]
            },
            "net": {
              "measurement": [
                "bytes_in",
                "bytes_out"
              ]
            }
          }
        }
      }

runcmd:
  - curl https://s3.us-east-2.amazonaws.com/aws-xray-assets.us-east-2/xray-daemon/aws-xray-daemon-3.x.rpm -o /home/ec2-user/xray.rpm
  - yum install -y amazon-cloudwatch-agent aws-cli icu /home/ec2-user/xray.rpm
  - mkdir -p /opt/kingmaker-discord-bot
  - aws s3 sync s3://{{ BUCKET }}/ /opt/kingmaker-discord-bot --region {{ REGION }}
  - chmod +x /opt/kingmaker-discord-bot/Application
  - systemctl daemon-reload
  - systemctl enable kingmaker-discord-bot
  - systemctl enable amazon-cloudwatch-agent
  - systemctl start amazon-cloudwatch-agent
  - systemctl start kingmaker-discord-bot
